apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler-api
        image: your-dockerhub-username/scheduler-api
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/scheduler"
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-api
spec:
  selector:
    app: scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
        