name: CI/CD for Distributed Task Scheduler

# Define the events that trigger the workflow
on:
  push:
    branches:
      - main    # Run this workflow when there is a push to the main branch
  pull_request:
    branches:
      - main    # Run this workflow when a pull request targets the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      # Uncomment if you want to run tests
      # - name: Run tests
      #   run: npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t rsubramani470/distributed-task-scheduler .
          docker push rsubramani470/distributed-task-scheduler

      - name: Set up kind (Kubernetes in Docker)
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes cluster
        run: kind create cluster

      - name: Set kubectl context to kind
        run: kubectl cluster-info --context kind-kind

      - name: Deploy to kind Kubernetes cluster
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/scheduler-api

      - name: Delete kind cluster
        run: kind delete cluster

